### ISSUE TITLE
audit rmw_fastrtps_cpp

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rmw_fastrtps#122]
meta-ticket, follow-up of #107 : 
includes
- [ ] audit calls to malloc and new and replace them if appropriate
- [ ] audit any function call that can throw and either catch them or replace them
- [ ] remove magic numbers: partially captured in  #72 
- [ ] remove irrelevant todos
- [ ] fix cleanup on all failure scenarios: catprued in  #33 
- [x] split functions.cpp in digestable files: done in #135
- [ ] replace assert with return with proper value and error messages
- [ ] audit sanity checks to make sure they make sense (e.g. https://github.com/ros2/rmw_fastrtps/pull/138#discussion_r132242929)

(feel free to complete this list I likely missed a few important items)

**Comment by mikaelarguedas** [comment]
refactor performed, audit not done yet

**Comment by clalancette** [comment]
Given the sheer age of this, I'm going to close it out.  All of the code can probably use an audit, but `rmw_fastrtps` is so different from when this is opened that I don't think the same things apply anymore.  If you disagree, feel free to reopen.
